const tripStart=new Date('2026-08-23T00:00:00+02:00');
const days=[
{d:'8/23',dow:'日',city:'羅馬',subtitle:'古羅馬初見',events:[['06:00','抵達 FCO 機場','機場入境、前往 The RomeHello 寄放行李','move'],['09:00','萬神殿・許願池','可彈性調整；中午前補水與休息','flex'],['11:55','抵達競技場','憑證要求提前 15 分鐘、攜帶有照片證件','fixed'],['12:10','Colosseum Full Experience — Attico','先直達電梯前往頂樓；競技場參觀限 90 分鐘','fixed'],['14:00','古羅馬廣場・帕拉提諾山','票券可在預約日前後各一天內使用一次','flex'],['17:30','The RomeHello 入住','Via Torino 45, Roma','stay']]},
{d:'8/24',dow:'一',city:'羅馬 → 佛羅倫斯',subtitle:'梵蒂岡與移動日',events:[['09:00','羅馬散步・退房寄行李','聖彼得大教堂僅視現場時間彈性安排','flex'],['12:30','抵達 Vatican Museums','Viale Vaticano 預約通道；出示證件及憑證','fixed'],['13:00','梵蒂岡博物館英文團體導覽','安檢後往入口大廳最左側樓梯，Guided Tours 櫃台報到','fixed'],['16:30','離館、取行李、前往 Termini','預留市區交通與車站緩衝','move'],['18:50','Roma Termini → Firenze S.M.N.','以 8/16 確認資訊為準；車票請存入票券庫','fixed'],['20:57','抵達佛羅倫斯','飯店入住、簡單晚餐','stay']]},
{d:'8/25',dow:'二',city:'佛羅倫斯',subtitle:'文藝復興核心',events:[['08:55','抵達烏菲茲入口','預留安檢與找入口時間','fixed'],['09:15','烏菲茲美術館','依 App 的 90–120 分鐘精華動線','fixed'],['12:00','中央市場・午餐','Nerbone 牛肚包或市場內彈性選擇','food'],['14:15','聖母百花大教堂登頂','此時間來自確認表；票券尚未在目前 Drive 資料夾中','fixed'],['18:30','米開朗基羅廣場夕陽','依體力調整，步行或公車上山','flex']]},
{d:'8/26',dow:'三',city:'佛羅倫斯',subtitle:'大衛與 Chianti',events:[['08:30','抵達學院美術館','提前 15 分鐘較安心','fixed'],['08:45','Galleria dell’Accademia','先直走大衛像，再看囚徒群像','fixed'],['10:15','聖羅倫佐・皮件市場','保留回飯店休息與午餐時間','flex'],['14:30','Chianti 葡萄酒與美食品鑑','憑證標題為 14:30 下午場，但內文另列 08:00 集合；務必向 KKday 確認','warn']]},
{d:'8/27',dow:'四',city:'比薩・五漁村',subtitle:'海岸一日遊',events:[['06:40','Piazzale Montelungo 集合','City Wonders 標誌；憑證要求至少提前 20 分鐘','fixed'],['07:00','比薩＋五漁村一日遊出發','電子憑證、護照或證件、好走的鞋與防曬','fixed'],['20:00','返回佛羅倫斯','實際回程依導遊通知','move']]},
{d:'8/28',dow:'五',city:'佛羅倫斯 → 米蘭',subtitle:'前往設計之都',events:[['08:30','佛羅倫斯高鐵 → Milano Centrale','班次來自原始行程；車票請存入票券庫','move'],['12:50','抵達米蘭大教堂 Gate 3 Verde','預留安檢','fixed'],['13:30','Duomo Fast-Track Pass・露台','時間是露台上行入口；下樓一律走樓梯','fixed'],['15:00','教堂內部・考古區','套票 2 天有效，每區限入一次；衣著遮肩膝','flex'],['18:00','布雷拉區散步','晚餐與採買','flex']]},
{d:'8/29',dow:'六',city:'米蘭',subtitle:'會議・Day 1',events:[['08:30','Allianz MiCo 研討會','建議使用 M5 紫線；實際議程請另存備註','fixed'],['18:00','CityLife 散步','依會議結束時間彈性安排','flex']]},
{d:'8/30',dow:'日',city:'米蘭',subtitle:'會議・Day 2',events:[['08:30','Allianz MiCo 研討會','票證與識別證前一晚放好','fixed'],['18:30','晚餐・自由活動','依會議行程調整','flex']]},
{d:'8/31',dow:'一',city:'米蘭',subtitle:'會議・Day 3',events:[['08:30','Allianz MiCo 研討會','午餐於會場或 CityLife','fixed'],['18:30','Lab 聚會／晚餐','集合資訊待補','flex']]},
{d:'9/1',dow:'二',city:'米蘭',subtitle:'會議・Day 4',events:[['08:30','Allianz MiCo 研討會','當日議程依大會公告','fixed'],['18:30','米蘭自由探索','依體力安排','flex']]},
{d:'9/2',dow:'三',city:'米蘭',subtitle:'會議閉幕',events:[['08:30','研討會最後一天','閉幕後處理行政事務','fixed'],['18:00','飯店休息・整理行李','準備會後旅行','flex']]},
{d:'9/3',dow:'四',city:'米蘭',subtitle:'最後的晚餐與城市精華',events:[['09:00','Cenacolo 售票處報到','憑證要求提前 30 分鐘，出示身分證件','fixed'],['09:15','前往博物館入口','憑證要求提前 15 分鐘到入口','fixed'],['09:30','《最後的晚餐》英文導覽','電子票直接以手機出示；不可更名','fixed'],['11:00','斯福爾扎城堡・市中心','依體力調整','flex'],['18:00','Navigli Aperitivo','運河區晚餐','food']]},
{d:'9/4',dow:'五',city:'科莫湖 → MXP',subtitle:'湖區慢旅行',events:[['08:00','前往 Como','實際車班請出發前確認','move'],['09:30','Como・Bellagio・Varenna','搭船順序依當日船班與天候彈性調整','flex'],['17:00','返回米蘭、取行李','預留轉往機場飯店時間','move'],['20:00','Holiday Inn Express Malpensa 入住','Via de Pinedo / Via Oldrini, Case Nuove；PIN 僅存於私人票券檔','stay']]},
{d:'9/5',dow:'六',city:'米蘭 → 台北',subtitle:'返程',events:[['07:30','前往 MXP 航廈','先確認航空公司航廈；辦理退稅','move'],['08:30','抵達機場・退稅與報到','國際線建議保留至少 3 小時','fixed'],['11:15','長榮直飛台北','航班資訊來自原始行程，請以電子機票最終確認','fixed']]}
];
const tickets=[
{id:'colosseum',date:'8/23 12:10',title:'羅馬競技場・Attico',note:'11:55 前抵達 · 帶證件 · 競技場 90 分鐘 · 禁帶大型行李',day:0},
{id:'rome-hotel',date:'8/23',title:'The RomeHello 住宿',note:'8/23–8/24 · Via Torino 45 · 2 人',day:0},
{id:'vatican',date:'8/24 13:00',title:'梵蒂岡博物館英文導覽',note:'12:30 報到 · Viale Vaticano · Guided Tours 櫃台 · 13 人',day:1},
{id:'uffizi',date:'8/25 09:15',title:'烏菲茲美術館',note:'手機電子票可直接出示 · 依現場展廳開放調整動線',day:2},
{id:'accademia',date:'8/26 08:45',title:'學院美術館',note:'Galleria dell’Accademia · 建議 08:30 抵達',day:3},
{id:'chianti',date:'8/26 14:30?',title:'Chianti 品酒一日遊',note:'⚠ 憑證場次 14:30，但內文集合 08:00；需向 KKday 確認',day:3},
{id:'cinque',date:'8/27 07:00',title:'比薩＋五漁村一日遊',note:'Piazzale Montelungo · 06:40 前抵達 · 4 人',day:4},
{id:'duomo',date:'8/28 13:30',title:'米蘭大教堂 Fast-Track',note:'Gate 3 Verde · 露台上行時間 · 下樓走樓梯 · 4 人',day:5},
{id:'milan-hotel',date:'8/28–9/4',title:'米蘭住宿',note:'住宿憑證可存入此卡；公開資料不含訂位碼',day:5},
{id:'cenacolo',date:'9/3 09:30',title:'《最後的晚餐》英文導覽',note:'09:00 售票處 · 帶證件 · 手機出示 · 不可更名',day:11},
{id:'mxp-hotel',date:'9/4',title:'Holiday Inn Express Malpensa',note:'14:00 後入住 · 9/5 12:00 前退房 · PIN 不寫入 App',day:12}
];
const guides=[
{id:'uffizi',city:'FIRENZE',title:'烏菲茲美術館',time:'90–120 分鐘',class:'',route:['Giotto','國際哥德式','Botticelli','Leonardo','Michelangelo','Raphael','Titian','Caravaggio'],stops:[['中世紀走向人性','先看 Giotto《聖母登基》：人物有重量、寶座有空間，這是從象徵走向真實的起點。'],['Botticelli 雙峰','《春》先找三美神與被追逐的 Chloris；《維納斯的誕生》看飄動輪廓，而非寫實解剖。'],['Leonardo 的空氣','《天使報喜》留意遠景如何因空氣而泛藍，及天使翅膀的自然研究。'],['文藝復興成熟期','Michelangelo《Doni Tondo》的扭轉肌肉，對照 Raphael 柔和而穩定的家庭金字塔。'],['威尼斯色彩與戲劇光','Titian 先看顏色塑形；Caravaggio《梅杜莎》則看瞬間恐懼與強烈明暗。']]},
{id:'vatican',city:'ROMA',title:'梵蒂岡博物館',time:'隨官方英文團',class:'rome',route:['入口','古典雕塑','Gallery of Maps','Raphael Rooms','Sistine Chapel'],stops:[['報到與起點','12:30 在 Viale Vaticano 外出示憑證與證件；安檢後走入口大廳最左側樓梯到 Guided Tours 櫃台。'],['古典雕塑','留意《拉奧孔》身體的螺旋扭動；它深刻影響 Michelangelo 對肌肉與動勢的理解。'],['地圖畫廊','不要只看地圖：抬頭看金色拱頂，理解 16 世紀教廷如何用地理描繪統一的義大利。'],['Raphael Rooms','《雅典學院》中柏拉圖向上、亞里斯多德向前；兩種手勢概括理念與經驗。'],['西斯廷禮拜堂','先看天頂中央九幕，再看祭壇牆《最後的審判》；現場保持安靜、禁止攝影。']]},
{id:'colosseum',city:'ROMA',title:'競技場 Attico',time:'90 分鐘',class:'rome',route:['入口','電梯','Attico','二層','一層'],stops:[['先上頂樓','入場後依憑證指示立即前往電梯。單向動線，不要離開標示路徑。'],['從 Attico 讀懂建築','向下看橢圓形競技場與地下層；外圈拱廊把人流迅速分散到不同座位階級。'],['權力與群眾','座位距離舞台的位置反映羅馬社會階級。競技不只是娛樂，也是帝國展示秩序的舞台。']]},
{id:'accademia',city:'FIRENZE',title:'學院美術館',time:'60–75 分鐘',class:'',route:['囚徒','David','石膏模型','樂器館'],stops:[['未完成的囚徒','先看人物像從石塊中掙脫；鑿痕讓你看到 Michelangelo 的創作過程。'],['David','繞一圈看放大的手與頭：作品原本預定放在高處。注意戰鬥前的專注，而不是勝利後的姿態。'],['完成與未完成','回望囚徒，再比較 David 光滑表面，感受 non-finito 如何讓石頭與肉身同時存在。']]},
{id:'duomo',city:'MILANO',title:'米蘭大教堂',time:'90 分鐘',class:'milan',route:['Gate 3','露台','下樓','教堂','考古區'],stops:[['露台森林','13:30 是露台上行入口時間。看飛扶壁、尖塔與大理石雕像如何把結構變成垂直的城市景觀。'],['金色 Madonnina','找最高尖塔上的金色聖母；她是米蘭城市象徵。下樓一律走樓梯。'],['教堂內部','留意彩繪玻璃與巨大柱列營造的尺度；進入需遮肩膝。'],['考古區','若開放，往下看早期基督教洗禮堂遺跡，理解今日大教堂疊建在更早的宗教中心上。']]},
{id:'cenacolo',city:'MILANO',title:'《最後的晚餐》',time:'15 分鐘＋導覽',class:'milan',route:['售票處','安檢','前室','壁畫'],stops:[['先看整體爆發','耶穌說出「有人將背叛我」後，十二門徒形成四組反應；中央耶穌仍是穩定三角形。'],['透視線','牆面與天花格線都集中到耶穌頭部，真實餐廳空間因此像向後延伸。'],['找出猶大','他與眾人同桌，身體後縮、手靠近錢袋；Leonardo 沒把他孤立到桌子另一側。'],['技法與脆弱','這不是傳統濕壁畫，實驗性乾壁技法讓細節更豐富，也使作品很早就開始劣化。']]}
];
let view='today',selectedDay=0,installPrompt=null,currentTicket=null;
const app=document.querySelector('#app'),title=document.querySelector('#pageTitle');
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function mapLinks(label){const q=encodeURIComponent(label);return `<div class="actions"><a href="https://maps.apple.com/?q=${q}" target="_blank" rel="noopener">Apple 地圖</a><a href="https://www.google.com/maps/search/?api=1&query=${q}" target="_blank" rel="noopener">Google Maps</a></div>`}
function eventHTML(e){let loc=e[1]; const typ=e[3];return `<div class="event"><div class="time">${e[0]}</div><div><h3>${e[1]}</h3><p>${e[2]}</p><div class="badges"><span class="badge ${typ==='fixed'?'fixed':typ==='warn'?'warn':''}">${typ==='fixed'?'固定時間':typ==='warn'?'待確認':typ==='move'?'移動':typ==='stay'?'住宿':typ==='food'?'用餐':'彈性安排'}</span></div>${mapLinks(loc)}</div></div>`}
function todayIndex(){const now=new Date(),start=new Date(2026,7,23),end=new Date(2026,8,5);if(now<start)return 0;if(now>end)return days.length-1;return Math.min(days.length-1,Math.floor((now-start)/86400000))}
function renderToday(){const i=todayIndex(),day=days[i],delta=Math.ceil((tripStart-new Date())/86400000);title.textContent='今天';app.innerHTML=`<section class="hero"><div class="date">${day.d} · ${day.dow}曜日</div><h2>${day.city}</h2><p>${day.subtitle}</p><div class="countdown">${delta>0?`距離出發還有 ${delta} 天`:'旅途中 · Buon viaggio!'}</div></section><div class="section-head"><h2>下一步</h2><button data-go-day="${i}">查看整天</button></div><section class="card">${day.events.slice(0,3).map(eventHTML).join('')}</section><div class="section-head"><h2>這天的票券</h2><button data-view-go="tickets">全部票券</button></div>${tickets.filter(t=>t.day===i).map(ticketHTML).join('')||'<div class="card empty">這天沒有已知票券</div>'}`}
function renderTimeline(){title.textContent='完整行程';const d=days[selectedDay];app.innerHTML=`<div class="date-strip">${days.map((x,i)=>`<button class="date-chip ${i===selectedDay?'active':''}" data-day="${i}"><small>${x.dow}</small><b>${x.d.split('/')[1]}</b><small>${x.d}</small></button>`).join('')}</div><div class="day-title"><div class="eyebrow">DAY ${selectedDay+1}</div><h2>${d.city}</h2><p>${d.d} · ${d.subtitle}</p></div>${selectedDay===3?'<div class="notice">重要：酒莊憑證的「14:30 下午場」與「08:00 集合」互相矛盾。出發前請向 KKday／Caf Tour & Travel 書面確認。</div>':''}<section class="card">${d.events.map(eventHTML).join('')}</section>`;document.querySelector('.date-chip.active')?.scrollIntoView({inline:'center',block:'nearest'})}
function ticketHTML(t){return `<article class="card ticket" data-ticket="${t.id}"><div class="ticket-top"><div><div class="eyebrow">TRAVEL PASS</div><h3>${t.title}</h3></div><div class="ticket-date">${t.date}</div></div><p>${t.note}</p><div class="actions"><button class="strong" data-upload="${t.id}">存入票券</button><button data-open="${t.id}">查看本機檔案</button></div></article>`}
async function renderTickets(){title.textContent='票券錢包';app.innerHTML=`<div class="privacy">🔒 PDF／圖片只保存在這台 iPhone 的瀏覽器資料庫，不會上傳到網站或寫入公開程式碼。建議出發前逐張存入並開啟確認。</div><div class="section-head"><h2>共 ${tickets.length} 個項目</h2></div>${tickets.map(ticketHTML).join('')}`;for(const t of tickets){if(await hasFile(t.id))document.querySelector(`[data-ticket="${t.id}"]`)?.classList.add('saved')}}
function renderGuides(){title.textContent='景點導覽';app.innerHTML=`<div class="notice">館內展廳與動線可能臨時調整；App 提供觀看順序，現場請以館方標示與工作人員指示為準。</div>${guides.map(g=>`<article class="card guide-card" data-guide="${g.id}"><div class="guide-cover ${g.class}"><div><div class="eyebrow" style="color:#f2c17d">${g.city} · ${g.time}</div><h3>${g.title}</h3></div></div><div class="guide-body"><div class="route">${g.route.map((x,i)=>`${i?'<i>›</i>':''}<span>${x}</span>`).join('')}</div><button class="primary" data-guide="${g.id}">開始導覽</button></div></article>`).join('')}`}
function renderMore(){title.textContent='旅行工具';app.innerHTML=`<section class="card"><h3>地圖與導航</h3><p class="muted">快速開啟本趟重點城市與集合點。</p>${['Roma Termini','Firenze Santa Maria Novella','Piazzale Montelungo Firenze','Allianz MiCo Milano','Milano Centrale','Malpensa Airport'].map(x=>`<div class="actions" style="justify-content:space-between"><b style="font-size:13px">${x}</b><a href="https://maps.apple.com/?q=${encodeURIComponent(x)}">導航</a></div>`).join('')}</section><section class="card"><h3>安裝到 iPhone 主畫面</h3><p class="muted">1. 用 Safari 開啟網站<br>2. 點底部「分享」<br>3. 選「加入主畫面」<br>4. 第一次連線開過後，行程與導覽可離線使用</p></section><section class="card"><h3>離線檢查</h3><p class="muted">出發前開啟每個頁面一次，並逐張打開已存票券。iPhone 若清除 Safari 網站資料，本機票券也會被刪除，請保留原始檔備份。</p><div class="actions"><button id="offlineTest" class="strong">重新下載離線內容</button></div></section><section class="card"><h3>緊急資訊</h3><p class="muted">歐盟緊急電話：112<br>義大利國碼：+39<br>護照、保險與信用卡掛失資料請另外離線保存。</p></section>`}
function setView(v){view=v;document.querySelectorAll('.tabbar button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));({today:renderToday,timeline:renderTimeline,tickets:renderTickets,guides:renderGuides,more:renderMore}[v])();scrollTo(0,0)}
function guideModal(id){const g=guides.find(x=>x.id===id);const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="sheet guide-detail"><div class="grabber"></div><button class="close" aria-label="關閉">×</button><div class="eyebrow">${g.city} · ${g.time}</div><h2>${g.title}</h2><div class="route">${g.route.map((x,i)=>`${i?'<i>›</i>':''}<span>${x}</span>`).join('')}</div>${g.stops.map((s,i)=>`<article class="card stop" data-n="${i+1}"><h3>${s[0]}</h3><p>${s[1]}</p></article>`).join('')}${mapLinks(g.title)}</div>`;document.body.append(m);m.querySelector('.close').onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()}}
const DB='italia-2026-vault';function db(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('files');r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}async function putFile(id,file){const d=await db();return new Promise((ok,no)=>{const tx=d.transaction('files','readwrite');tx.objectStore('files').put({name:file.name,type:file.type,data:file,updated:Date.now()},id);tx.oncomplete=ok;tx.onerror=()=>no(tx.error)})}async function getFile(id){const d=await db();return new Promise((ok,no)=>{const r=d.transaction('files').objectStore('files').get(id);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}async function hasFile(id){return !!(await getFile(id))}
document.addEventListener('click',async e=>{const b=e.target.closest('button,[data-guide]');if(!b)return;if(b.dataset.view)setView(b.dataset.view);if(b.dataset.viewGo)setView(b.dataset.viewGo);if(b.dataset.day!==undefined){selectedDay=+b.dataset.day;renderTimeline()}if(b.dataset.goDay!==undefined){selectedDay=+b.dataset.goDay;setView('timeline')}if(b.dataset.guide)guideModal(b.dataset.guide);if(b.dataset.upload){currentTicket=b.dataset.upload;document.querySelector('#fileInput').click()}if(b.dataset.open){const f=await getFile(b.dataset.open);if(!f)return alert('尚未在這台裝置存入檔案。');open(URL.createObjectURL(f.data),'_blank')}if(b.id==='offlineTest'){const reg=await navigator.serviceWorker?.getRegistration();await reg?.update();alert('離線內容已更新。')}});
document.querySelector('#fileInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>20*1024*1024)return alert('單一檔案請小於 20 MB。');await putFile(currentTicket,f);e.target.value='';renderTickets()};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;document.querySelector('#installBtn').hidden=false});document.querySelector('#installBtn').onclick=()=>installPrompt?.prompt();
function online(){document.querySelector('#offlineBanner').hidden=navigator.onLine}window.addEventListener('online',online);window.addEventListener('offline',online);online();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');setView('today');
